// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW8KWuljBIZgduks6cafAVGBHCUAhuAyA',
    appId: '1:572896190891:web:ef86cd51a9a5f1737372ee',
    messagingSenderId: '572896190891',
    projectId: 'beautyapp-61e36',
    authDomain: 'beautyapp-61e36.firebaseapp.com',
    storageBucket: 'beautyapp-61e36.firebasestorage.app',
    measurementId: 'G-SSMJS5D0C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6TOpomGI8QLpJwjvumSJZoYAhLB6v_NM',
    appId: '1:572896190891:android:714eed90d24d8c9c7372ee',
    messagingSenderId: '572896190891',
    projectId: 'beautyapp-61e36',
    storageBucket: 'beautyapp-61e36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD28iZj9WFkZctaU_XlhRRUlpQpPFVmZ0',
    appId: '1:572896190891:ios:979a91ad245cd11d7372ee',
    messagingSenderId: '572896190891',
    projectId: 'beautyapp-61e36',
    storageBucket: 'beautyapp-61e36.firebasestorage.app',
    iosBundleId: 'com.example.beautyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD28iZj9WFkZctaU_XlhRRUlpQpPFVmZ0',
    appId: '1:572896190891:ios:979a91ad245cd11d7372ee',
    messagingSenderId: '572896190891',
    projectId: 'beautyapp-61e36',
    storageBucket: 'beautyapp-61e36.firebasestorage.app',
    iosBundleId: 'com.example.beautyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW8KWuljBIZgduks6cafAVGBHCUAhuAyA',
    appId: '1:572896190891:web:38936242f01a56f07372ee',
    messagingSenderId: '572896190891',
    projectId: 'beautyapp-61e36',
    authDomain: 'beautyapp-61e36.firebaseapp.com',
    storageBucket: 'beautyapp-61e36.firebasestorage.app',
    measurementId: 'G-T8RFMCT164',
  );
}
